# Uncomment this line to define a global platform for your project
platform :ios, "6.1"

pod 'CocoaSoundCloudAPI', '~> 1.0.2'
pod 'CocoaSoundCloudUI', '~> 1.0.7'

target "RPG-Soundmaster" do
    pod 'CocoaSoundCloudAPI', '~> 1.0.2'
    pod 'CocoaSoundCloudUI', '~> 1.0.7'
end

target "RPG-SoundmasterTests" do
    pod 'CocoaSoundCloudAPI', '~> 1.0.2'
    pod 'CocoaSoundCloudUI', '~> 1.0.7'
end

