# Uncomment this line to define a global platform for your project
platform :ios, "6.1"

inhibit_all_warnings!

target "RPG-Soundmaster" do
    pod 'CocoaSoundCloudAPI'
    pod 'CocoaSoundCloudUI'
    pod 'RestKit'
end

target "RPG-SoundmasterTests" do
    pod 'CocoaSoundCloudAPI'
    pod 'CocoaSoundCloudUI'
end

